### ISSUE TITLE
Migrate test pipelines to GH actions

### ISSUE THREAD

**Issue by mikeharder** [Azure/openapi-diff#330]

**Comment by konrad-jamrozik** [comment]
@mikeharder so I merged this:

- https://github.com/Azure/openapi-diff/pull/339

And here is an example run:

- https://github.com/Azure/openapi-diff/actions/runs/9754446026#artifacts

Now, ignoring the warnings about deprecated action versions for a moment.

Per @scbedd package publication to public package manager must go through official 1ES templates. In this repo this happens via Azure DevOps pipeline, which depends on building as seen here:

- https://github.com/Azure/openapi-diff/blob/9f15b9300d77b1a9201461f5392825b8c6929f6f/azure-pipelines.yml#L41

Hence now that we have GitHub action also building and testing, we have duplication. To deduplicate we would have to ensure that the drop from GitHub action is taken as input by the ADO pipeline doing the publishing. I think it reads the drop in these lines:

- https://github.com/Azure/openapi-diff/blob/9f15b9300d77b1a9201461f5392825b8c6929f6f/azure-pipelines.yml#L58-L59

Do you have any experience with reading from ADO pipeline a drop made by GitHub actions? 

I think it would be worthwhile for us to figure this out, otherwise we would have to maintain build ADO pipeline for all our tools that publish to public package manager.

**Comment by konrad-jamrozik** [comment]
Per my chat with @mikeharder:

- For publishing packages, we must retain entire supply chain on 1ES agents. Perhaps there exists a GH actions based solution, but for now we are using the ADO pipelines-based solution.
- We still want to retain GH actions but only for rapid building and testing. The ADO pipeline is used only for publishing new package version. Hence I will remove everything after test task from the GH action.
